import type { IconSvgElement } from '@hugeicons/react'
import {
  Award01Icon,
  ChartUpIcon,
  Money01Icon,
  StarIcon,
  EyeIcon,
} from '@hugeicons/core-free-icons'

export interface Achievement {
  id: string
  name: string
  description: string
  icon: IconSvgElement
  earned: boolean
  earnedDate?: string
  rarity: 'common' | 'rare' | 'epic' | 'legendary'
}

export interface MatchRecord {
  id: string
  tournament: string
  game: string
  opponent: string
  result: 'win' | 'loss'
  prize: string
  date: string
  round: string
}

export interface PlayerData {
  handle: string
  displayName: string
  city: string
  region: string
  primaryGame: string
  vertical: string
  rank: string
  tier: 'Bronze' | 'Silver' | 'Gold' | 'Platinum' | 'Diamond' | 'Obsidian'
  tierProgress: number
  bio: string
  totalEarnings: string
  tournamentsPlayed: number
  winRate: string
  wins: number
  losses: number
  currentStreak: number
  streakType: 'win' | 'loss'
  leaderboardRank: number
  joinedDate: string
  team?: string
  achievements: Achievement[]
  matchHistory: MatchRecord[]
}

export const playersData: PlayerData[] = [
  {
    handle: 'GhostAlpha',
    displayName: '@GhostAlpha',
    city: 'Lagos',
    region: 'Nigeria',
    primaryGame: 'COD Mobile',
    vertical: 'Gaming',
    rank: 'Obsidian I',
    tier: 'Obsidian',
    tierProgress: 78,
    bio: 'Pro COD Mobile player. Top 50 Africa. Competing since Season 1.',
    totalEarnings: '₦450,000',
    tournamentsPlayed: 24,
    winRate: '68%',
    wins: 16,
    losses: 8,
    currentStreak: 4,
    streakType: 'win',
    leaderboardRank: 1,
    joinedDate: 'Jan 2026',
    team: 'Team Nexus',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',           icon: Award01Icon,  earned: true,  earnedDate: 'Feb 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',              icon: ChartUpIcon,  earned: true,  earnedDate: 'Mar 2026', rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',     icon: Money01Icon,  earned: true,  earnedDate: 'Apr 2026', rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',             icon: StarIcon,     earned: true,  earnedDate: 'May 2026', rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',            icon: Award01Icon,  earned: true,  earnedDate: 'Jun 2026', rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',   icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win tournaments in 3 different verticals', icon: Award01Icon, earned: false,                     rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa leaderboard', icon: StarIcon,   earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'Lagos Arena — CODM Cup',       game: 'COD Mobile', opponent: '@Shadow_NG',    result: 'win',  prize: '₦100,000', date: 'Jun 28, 2026', round: 'Grand Final'    },
      { id: '2', tournament: 'CODM Lagos Qualifiers S1',     game: 'COD Mobile', opponent: '@KanoKing',     result: 'win',  prize: '₦45,000',  date: 'Jun 21, 2026', round: 'Semi Final'     },
      { id: '3', tournament: 'West Africa CODM Open',        game: 'COD Mobile', opponent: '@AceShooterPH', result: 'win',  prize: '₦30,000',  date: 'Jun 14, 2026', round: 'Quarter Final'  },
      { id: '4', tournament: 'Nigeria FPS Championship',     game: 'COD Mobile', opponent: '@ZuluSquad',    result: 'loss', prize: '—',         date: 'Jun 7, 2026',  round: 'Semi Final'     },
      { id: '5', tournament: 'Lagos Arena — CODM Cup',       game: 'COD Mobile', opponent: '@QueenPlays',   result: 'win',  prize: '₦25,000',  date: 'May 30, 2026', round: 'Quarter Final'  },
      { id: '6', tournament: 'KultVibe Season 0 Finals',     game: 'COD Mobile', opponent: '@NaijaNinja',   result: 'win',  prize: '₦75,000',  date: 'May 15, 2026', round: 'Grand Final'    },
    ],
  },
  {
    handle: 'ZuluSquad',
    displayName: '@ZuluSquad',
    city: 'Abuja',
    region: 'Nigeria',
    primaryGame: 'PUBG Mobile',
    vertical: 'Gaming',
    rank: 'Diamond II',
    tier: 'Diamond',
    tierProgress: 54,
    bio: 'PUBG Mobile squad leader from Abuja. Africa top 100.',
    totalEarnings: '₦380,000',
    tournamentsPlayed: 18,
    winRate: '61%',
    wins: 11,
    losses: 7,
    currentStreak: 2,
    streakType: 'win',
    leaderboardRank: 2,
    joinedDate: 'Feb 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',           icon: Award01Icon,  earned: true,  earnedDate: 'Mar 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',              icon: ChartUpIcon,  earned: true,  earnedDate: 'Apr 2026', rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',     icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',             icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',            icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',   icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win tournaments in 3 different verticals', icon: Award01Icon, earned: false,                     rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa leaderboard', icon: StarIcon,   earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'PUBG Naija Royale',           game: 'PUBG Mobile', opponent: '@LagosLoot',    result: 'win',  prize: '₦250,000', date: 'Jul 1, 2026',  round: 'Grand Final'  },
      { id: '2', tournament: 'PUBG Africa Squads Open',     game: 'PUBG Mobile', opponent: '@AceShooterPH', result: 'win',  prize: '₦80,000',  date: 'Jun 20, 2026', round: 'Semi Final'   },
      { id: '3', tournament: 'Nigeria Battle Royale Cup',   game: 'PUBG Mobile', opponent: '@GhostAlpha',   result: 'loss', prize: '—',         date: 'Jun 7, 2026',  round: 'Semi Final'   },
    ],
  },
  {
    handle: 'Kelechi_FC',
    displayName: '@Kelechi_FC',
    city: 'Port Harcourt',
    region: 'Nigeria',
    primaryGame: 'EA FC',
    vertical: 'Gaming',
    rank: 'Diamond I',
    tier: 'Diamond',
    tierProgress: 82,
    bio: 'EA FC street league specialist. Top 3 Nigeria. 1v1 ranked grinder.',
    totalEarnings: '₦290,000',
    tournamentsPlayed: 31,
    winRate: '55%',
    wins: 17,
    losses: 14,
    currentStreak: 3,
    streakType: 'win',
    leaderboardRank: 3,
    joinedDate: 'Feb 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'Mar 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: true,  earnedDate: 'May 2026', rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'EA FC Street League S2',     game: 'EA FC', opponent: '@ZuluSquad',   result: 'win',  prize: '₦80,000',  date: 'Jun 25, 2026', round: 'Grand Final'   },
      { id: '2', tournament: 'Nigeria FIFA Championship',  game: 'EA FC', opponent: '@GhostAlpha',  result: 'loss', prize: '—',         date: 'Jun 10, 2026', round: 'Semi Final'    },
      { id: '3', tournament: 'EA FC Street League S1',     game: 'EA FC', opponent: '@NaijaNinja',  result: 'win',  prize: '₦55,000',  date: 'May 20, 2026', round: 'Grand Final'   },
    ],
  },
  {
    handle: 'Shadow_NG',
    displayName: '@Shadow_NG',
    city: 'Lagos',
    region: 'Nigeria',
    primaryGame: 'COD Mobile',
    vertical: 'Gaming',
    rank: 'Platinum II',
    tier: 'Platinum',
    tierProgress: 45,
    bio: 'Free Fire and COD Mobile grinder from Lagos. Diamond push in progress.',
    totalEarnings: '₦180,000',
    tournamentsPlayed: 20,
    winRate: '47%',
    wins: 10,
    losses: 10,
    currentStreak: 1,
    streakType: 'win',
    leaderboardRank: 5,
    joinedDate: 'Mar 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'Apr 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'Lagos Arena — CODM Cup',    game: 'COD Mobile', opponent: '@GhostAlpha', result: 'loss', prize: '—',        date: 'Jun 28, 2026', round: 'Grand Final'  },
      { id: '2', tournament: 'West Africa CODM Open',     game: 'COD Mobile', opponent: '@KanoKing',   result: 'win',  prize: '₦40,000', date: 'Jun 15, 2026', round: 'Quarter Final' },
      { id: '3', tournament: 'Nigeria FPS Championship',  game: 'COD Mobile', opponent: '@AmaGamer',   result: 'win',  prize: '₦30,000', date: 'Jun 1, 2026',  round: 'Semi Final'   },
    ],
  },
  {
    handle: 'AfroBeatz',
    displayName: '@AfroBeatz',
    city: 'Lagos',
    region: 'Nigeria',
    primaryGame: 'Music · Beat Battle',
    vertical: 'Music',
    rank: 'Gold II',
    tier: 'Gold',
    tierProgress: 60,
    bio: 'Beat Battle Lagos finalist. Afrobeats producer and live streamer.',
    totalEarnings: '₦142,000',
    tournamentsPlayed: 9,
    winRate: '56%',
    wins: 5,
    losses: 4,
    currentStreak: 2,
    streakType: 'win',
    leaderboardRank: 7,
    joinedDate: 'Mar 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'Apr 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'Beat Battle Lagos Finals',  game: 'Music · Beat Battle', opponent: '@DrumKingKano', result: 'win',  prize: '₦75,000', date: 'Jun 22, 2026', round: 'Grand Final'  },
      { id: '2', tournament: 'Beat Battle Lagos Round 1', game: 'Music · Beat Battle', opponent: '@VibeLensLagos',result: 'win',  prize: '₦20,000', date: 'Jun 8, 2026',  round: 'Quarter Final' },
      { id: '3', tournament: 'Naija Sound Clash',         game: 'Music · Beat Battle', opponent: '@DrumKingKano', result: 'loss', prize: '—',        date: 'May 18, 2026', round: 'Semi Final'   },
    ],
  },
  {
    handle: 'ProCoderLagos',
    displayName: '@ProCoderLagos',
    city: 'Lagos',
    region: 'Nigeria',
    primaryGame: 'Tech & Dev',
    vertical: 'Tech & Dev',
    rank: 'Gold I',
    tier: 'Gold',
    tierProgress: 88,
    bio: 'CTF champion and competitive coder. First place Naija CTF Challenge.',
    totalEarnings: '₦120,000',
    tournamentsPlayed: 7,
    winRate: '71%',
    wins: 5,
    losses: 2,
    currentStreak: 3,
    streakType: 'win',
    leaderboardRank: 8,
    joinedDate: 'Apr 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'Apr 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'Naija CTF Challenge',      game: 'Tech & Dev', opponent: '@AbujaCoder',    result: 'win',  prize: '₦150,000', date: 'Jun 20, 2026', round: 'Grand Final'  },
      { id: '2', tournament: 'Lagos Hackathon Open',     game: 'Tech & Dev', opponent: '@VibeLensLagos', result: 'win',  prize: '₦50,000',  date: 'Jun 5, 2026',  round: 'Semi Final'   },
      { id: '3', tournament: 'West Africa Code Battle',  game: 'Tech & Dev', opponent: '@AbujaCoder',    result: 'loss', prize: '—',         date: 'May 22, 2026', round: 'Quarter Final'},
    ],
  },
  {
    handle: 'QueenPlays',
    displayName: '@QueenPlays',
    city: 'Lagos',
    region: 'Nigeria',
    primaryGame: 'Valorant',
    vertical: 'Gaming',
    rank: 'Gold III',
    tier: 'Gold',
    tierProgress: 30,
    bio: 'Valorant ACT III ranked player. One of Lagos\'s top female competitors.',
    totalEarnings: '₦105,000',
    tournamentsPlayed: 14,
    winRate: '43%',
    wins: 6,
    losses: 8,
    currentStreak: 1,
    streakType: 'loss',
    leaderboardRank: 9,
    joinedDate: 'Feb 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'Mar 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'Lagos Arena — CODM Cup',  game: 'Valorant',    opponent: '@GhostAlpha', result: 'loss', prize: '—',        date: 'May 30, 2026', round: 'Quarter Final' },
      { id: '2', tournament: 'Valorant Lagos Open',     game: 'Valorant',    opponent: '@Shadow_NG',  result: 'win',  prize: '₦60,000', date: 'May 14, 2026', round: 'Grand Final'   },
      { id: '3', tournament: 'Africa Valorant Clash',   game: 'Valorant',    opponent: '@AmaGamer',   result: 'loss', prize: '—',        date: 'May 1, 2026',  round: 'Semi Final'    },
    ],
  },
  {
    handle: 'NaijaNinja',
    displayName: '@NaijaNinja',
    city: 'Lagos',
    region: 'Nigeria',
    primaryGame: 'Mortal Kombat 1',
    vertical: 'Gaming',
    rank: 'Silver I',
    tier: 'Silver',
    tierProgress: 70,
    bio: 'MK1 ranked grinder, Road to God of War. Lagos fighting game scene.',
    totalEarnings: '₦98,000',
    tournamentsPlayed: 11,
    winRate: '45%',
    wins: 5,
    losses: 6,
    currentStreak: 1,
    streakType: 'loss',
    leaderboardRank: 10,
    joinedDate: 'Mar 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'Apr 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'KultVibe Season 0 Finals',  game: 'Mortal Kombat 1', opponent: '@GhostAlpha',  result: 'loss', prize: '—',        date: 'May 15, 2026', round: 'Grand Final'  },
      { id: '2', tournament: 'Lagos FGC Open',            game: 'Mortal Kombat 1', opponent: '@Kelechi_FC',  result: 'loss', prize: '—',        date: 'May 2, 2026',  round: 'Semi Final'   },
      { id: '3', tournament: 'Nigeria MK1 Cup',           game: 'Mortal Kombat 1', opponent: '@AmaGamer',    result: 'win',  prize: '₦35,000', date: 'Apr 18, 2026', round: 'Grand Final'  },
    ],
  },
  {
    handle: 'DrumKingKano',
    displayName: '@DrumKingKano',
    city: 'Kano',
    region: 'Nigeria',
    primaryGame: 'Music · Afrobeats',
    vertical: 'Music',
    rank: 'Gold II',
    tier: 'Gold',
    tierProgress: 50,
    bio: 'Afrobeats production session host from Kano. New EP in the works.',
    totalEarnings: '₦157,500',
    tournamentsPlayed: 12,
    winRate: '58%',
    wins: 7,
    losses: 5,
    currentStreak: 2,
    streakType: 'win',
    leaderboardRank: 6,
    joinedDate: 'Feb 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'Mar 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'Beat Battle Lagos Finals',  game: 'Music · Afrobeats', opponent: '@AfroBeatz',     result: 'loss', prize: '—',        date: 'Jun 22, 2026', round: 'Grand Final'  },
      { id: '2', tournament: 'Naija Sound Clash',         game: 'Music · Afrobeats', opponent: '@AfroBeatz',     result: 'win',  prize: '₦50,000', date: 'May 18, 2026', round: 'Semi Final'   },
      { id: '3', tournament: 'Kano Music Battle S1',      game: 'Music · Afrobeats', opponent: '@VibeLensLagos', result: 'win',  prize: '₦40,000', date: 'May 4, 2026',  round: 'Grand Final'  },
    ],
  },
  {
    handle: 'AmaGamer',
    displayName: '@AmaGamer',
    city: 'Kano',
    region: 'Nigeria',
    primaryGame: 'Free Fire',
    vertical: 'Gaming',
    rank: 'Platinum I',
    tier: 'Platinum',
    tierProgress: 20,
    bio: 'Free Fire ranked player from Kano. Grinding Diamond.',
    totalEarnings: '₦215,000',
    tournamentsPlayed: 15,
    winRate: '50%',
    wins: 8,
    losses: 7,
    currentStreak: 1,
    streakType: 'win',
    leaderboardRank: 4,
    joinedDate: 'Jan 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'Feb 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'Free Fire Kano Open',      game: 'Free Fire', opponent: '@KanoKing',   result: 'win',  prize: '₦70,000', date: 'Jun 18, 2026', round: 'Grand Final'  },
      { id: '2', tournament: 'Nigeria Battle Royale Cup',game: 'Free Fire', opponent: '@Shadow_NG',  result: 'loss', prize: '—',        date: 'Jun 1, 2026',  round: 'Semi Final'   },
      { id: '3', tournament: 'West Africa FF Open',      game: 'Free Fire', opponent: '@AceShooterPH',result: 'win', prize: '₦50,000', date: 'May 15, 2026', round: 'Quarter Final'},
    ],
  },
  {
    handle: 'LagosLoot',
    displayName: '@LagosLoot',
    city: 'Lagos',
    region: 'Nigeria',
    primaryGame: 'Fortnite',
    vertical: 'Gaming',
    rank: 'Silver II',
    tier: 'Silver',
    tierProgress: 40,
    bio: 'Fortnite Chapter 5 solo arena specialist. Building to the top.',
    totalEarnings: '₦85,000',
    tournamentsPlayed: 8,
    winRate: '38%',
    wins: 3,
    losses: 5,
    currentStreak: 2,
    streakType: 'loss',
    leaderboardRank: 11,
    joinedDate: 'Apr 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'May 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'PUBG Naija Royale',         game: 'Fortnite', opponent: '@ZuluSquad',    result: 'loss', prize: '—',        date: 'Jul 1, 2026',  round: 'Grand Final'  },
      { id: '2', tournament: 'Lagos Fortnite Open',       game: 'Fortnite', opponent: '@AmaGamer',     result: 'win',  prize: '₦45,000', date: 'Jun 10, 2026', round: 'Grand Final'  },
      { id: '3', tournament: 'Nigeria Battle Royale Cup', game: 'Fortnite', opponent: '@NaijaNinja',   result: 'loss', prize: '—',        date: 'May 25, 2026', round: 'Quarter Final'},
    ],
  },
  {
    handle: 'AceShooterPH',
    displayName: '@AceShooterPH',
    city: 'Port Harcourt',
    region: 'Nigeria',
    primaryGame: 'Free Fire',
    vertical: 'Gaming',
    rank: 'Silver III',
    tier: 'Silver',
    tierProgress: 15,
    bio: 'Free Fire Clash Squad specialist from Port Harcourt. Diamond ranked.',
    totalEarnings: '₦72,000',
    tournamentsPlayed: 6,
    winRate: '42%',
    wins: 3,
    losses: 3,
    currentStreak: 1,
    streakType: 'win',
    leaderboardRank: 12,
    joinedDate: 'Apr 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'May 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'West Africa CODM Open',    game: 'Free Fire', opponent: '@GhostAlpha', result: 'loss', prize: '—',        date: 'Jun 14, 2026', round: 'Quarter Final'},
      { id: '2', tournament: 'PUBG Africa Squads Open',  game: 'Free Fire', opponent: '@ZuluSquad',  result: 'loss', prize: '—',        date: 'Jun 20, 2026', round: 'Semi Final'   },
      { id: '3', tournament: 'Free Fire PH Open',        game: 'Free Fire', opponent: '@AmaGamer',   result: 'win',  prize: '₦30,000', date: 'May 28, 2026', round: 'Grand Final'  },
    ],
  },
  {
    handle: 'VibeLensLagos',
    displayName: '@VibeLensLagos',
    city: 'Lagos',
    region: 'Nigeria',
    primaryGame: 'Lifestyle',
    vertical: 'Lifestyle',
    rank: 'Silver II',
    tier: 'Silver',
    tierProgress: 65,
    bio: 'Lagos street photographer and culture documentarian. Newest face on KultVibe.',
    totalEarnings: '₦68,000',
    tournamentsPlayed: 5,
    winRate: '60%',
    wins: 3,
    losses: 2,
    currentStreak: 2,
    streakType: 'win',
    leaderboardRank: 13,
    joinedDate: 'Jun 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'Jun 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'Kano Music Battle S1',   game: 'Lifestyle', opponent: '@DrumKingKano',  result: 'loss', prize: '—',        date: 'May 4, 2026',  round: 'Grand Final'  },
      { id: '2', tournament: 'Lagos Creator Cup',      game: 'Lifestyle', opponent: '@AfroBeatz',     result: 'win',  prize: '₦40,000', date: 'Apr 22, 2026', round: 'Grand Final'  },
      { id: '3', tournament: 'Lagos Hackathon Open',   game: 'Lifestyle', opponent: '@ProCoderLagos', result: 'loss', prize: '—',        date: 'Jun 5, 2026',  round: 'Semi Final'   },
    ],
  },
  {
    handle: 'AbujaCoder',
    displayName: '@AbujaCoder',
    city: 'Abuja',
    region: 'Nigeria',
    primaryGame: 'Tech & Dev',
    vertical: 'Tech & Dev',
    rank: 'Bronze II',
    tier: 'Bronze',
    tierProgress: 60,
    bio: 'Competitive coder from Abuja. Grinding through the Tech & Dev vertical.',
    totalEarnings: '₦59,000',
    tournamentsPlayed: 4,
    winRate: '50%',
    wins: 2,
    losses: 2,
    currentStreak: 1,
    streakType: 'loss',
    leaderboardRank: 14,
    joinedDate: 'May 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: true,  earnedDate: 'May 2026', rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'Naija CTF Challenge',     game: 'Tech & Dev', opponent: '@ProCoderLagos', result: 'loss', prize: '—',        date: 'Jun 20, 2026', round: 'Grand Final'  },
      { id: '2', tournament: 'West Africa Code Battle', game: 'Tech & Dev', opponent: '@ProCoderLagos', result: 'win',  prize: '₦35,000', date: 'May 22, 2026', round: 'Quarter Final'},
      { id: '3', tournament: 'Abuja Dev Open',          game: 'Tech & Dev', opponent: '@VibeLensLagos', result: 'win',  prize: '₦25,000', date: 'May 8, 2026',  round: 'Grand Final'  },
    ],
  },
  {
    handle: 'KanoKing',
    displayName: '@KanoKing',
    city: 'Kano',
    region: 'Nigeria',
    primaryGame: 'COD Mobile',
    vertical: 'Gaming',
    rank: 'Bronze I',
    tier: 'Bronze',
    tierProgress: 35,
    bio: 'COD Mobile up-and-comer from Kano. Gifting big, playing bigger.',
    totalEarnings: '₦45,000',
    tournamentsPlayed: 3,
    winRate: '33%',
    wins: 1,
    losses: 2,
    currentStreak: 2,
    streakType: 'loss',
    leaderboardRank: 15,
    joinedDate: 'May 2026',
    achievements: [
      { id: '1', name: 'First Blood',     description: 'Win your first tournament',        icon: Award01Icon,  earned: false,                          rarity: 'common'    },
      { id: '2', name: 'Hot Streak',      description: 'Win 5 matches in a row',           icon: ChartUpIcon,  earned: false,                          rarity: 'rare'      },
      { id: '3', name: 'Top Earner',      description: 'Earn ₦100,000 in a single month',  icon: Money01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '4', name: 'Lagos Legend',    description: 'Rank #1 in Lagos region',          icon: StarIcon,     earned: false,                          rarity: 'legendary' },
      { id: '5', name: 'Obsidian Tier',   description: 'Reach Obsidian rank tier',         icon: Award01Icon,  earned: false,                          rarity: 'legendary' },
      { id: '6', name: 'Untouchable',     description: 'Win 10 tournaments without a loss',icon: EyeIcon,      earned: false,                          rarity: 'legendary' },
      { id: '7', name: 'Grand Slam',      description: 'Win in 3 different verticals',     icon: Award01Icon,  earned: false,                          rarity: 'epic'      },
      { id: '8', name: 'Africa Champion', description: 'Rank #1 on the All Africa board',  icon: StarIcon,     earned: false,                          rarity: 'legendary' },
    ],
    matchHistory: [
      { id: '1', tournament: 'CODM Lagos Qualifiers S1',  game: 'COD Mobile', opponent: '@GhostAlpha', result: 'loss', prize: '—',        date: 'Jun 21, 2026', round: 'Semi Final'   },
      { id: '2', tournament: 'West Africa CODM Open',     game: 'COD Mobile', opponent: '@Shadow_NG',  result: 'loss', prize: '—',        date: 'Jun 15, 2026', round: 'Quarter Final'},
      { id: '3', tournament: 'Free Fire Kano Open',       game: 'COD Mobile', opponent: '@AmaGamer',   result: 'win',  prize: '₦25,000', date: 'Jun 5, 2026',  round: 'Grand Final'  },
    ],
  },
]

export function getPlayerByHandle(handle: string) {
  const normalize = (s: string) => s.toLowerCase().replace(/_/g, '')
  return playersData.find((p) => normalize(p.handle) === normalize(handle))
}

export const tierColors: Record<string, { bg: string; text: string; border: string; glow: string }> = {
  Bronze:   { bg: 'rgba(205,127,50,0.15)',  text: '#CD7F32', border: 'rgba(205,127,50,0.3)',  glow: 'rgba(205,127,50,0.1)'  },
  Silver:   { bg: 'rgba(192,192,192,0.15)', text: '#C0C0C0', border: 'rgba(192,192,192,0.3)', glow: 'rgba(192,192,192,0.1)' },
  Gold:     { bg: 'rgba(240,180,41,0.15)',  text: '#F0B429', border: 'rgba(240,180,41,0.3)',  glow: 'rgba(240,180,41,0.1)'  },
  Platinum: { bg: 'rgba(16,185,129,0.15)',  text: '#10B981', border: 'rgba(16,185,129,0.3)',  glow: 'rgba(16,185,129,0.1)'  },
  Diamond:  { bg: 'rgba(96,165,250,0.15)',  text: '#60A5FA', border: 'rgba(96,165,250,0.3)',  glow: 'rgba(96,165,250,0.1)'  },
  Obsidian: { bg: 'rgba(167,139,250,0.15)', text: '#A78BFA', border: 'rgba(167,139,250,0.3)', glow: 'rgba(167,139,250,0.1)' },
}
