export interface StreamData {
  id: string
  title: string
  streamer: string
  city: string
  viewers: number
  game: string
  category: string
  tags: string[]
  isLive: boolean
  videoSrc?: string
  gradientFrom?: string
  gradientTo?: string
  followers: string
  bio: string
  socials: { platform: string; handle: string; url: string }[]
  goal: { label: string; current: number; target: number }
}

export const streamsData: StreamData[] = [
  // --- Live ---
  {
    id: 'ghostalpha',
    title: 'CODM — Lagos Qualifiers · Season 1',
    streamer: '@GhostAlpha',
    city: 'Lagos',
    viewers: 1280,
    game: 'COD Mobile',
    category: 'Gaming',
    tags: ['RANKED', 'NIGERIA'],
    isLive: true,
    videoSrc: '/videos/featured-stream.mp4',
    followers: '24.5K',
    bio: 'Pro COD Mobile player 🎮 | Top 50 Africa | Content creator & grinder. Streaming daily from Lagos.',
    socials: [
      { platform: 'instagram', handle: 'ghostalpha', url: '#' },
      { platform: 'x',         handle: 'ghostalpha', url: '#' },
      { platform: 'tiktok',    handle: 'ghostalpha', url: '#' },
      { platform: 'discord',   handle: 'ghostalpha', url: '#' },
      { platform: 'youtube',   handle: 'ghostalpha', url: '#' },
    ],
    goal: { label: 'Followers to next milestone', current: 24500, target: 30000 },
  },
  {
    id: 'zulusquad',
    title: 'PUBG Naija Royale — Squad Push',
    streamer: '@ZuluSquad',
    city: 'Abuja',
    viewers: 940,
    game: 'PUBG Mobile',
    category: 'Gaming',
    tags: ['SQUADS', 'AFRICA'],
    isLive: true,
    videoSrc: '/videos/stream-pubg.mp4',
    followers: '18.2K',
    bio: 'PUBG Mobile squad leader. Abuja based. Daily squad push streams, road to top 10 Africa.',
    socials: [
      { platform: 'instagram', handle: 'zulusquad', url: '#' },
      { platform: 'tiktok',    handle: 'zulusquad', url: '#' },
      { platform: 'discord',   handle: 'zulusquad', url: '#' },
    ],
    goal: { label: 'Subs to next tournament sponsorship', current: 142, target: 200 },
  },
  {
    id: 'afrobeatz',
    title: 'Beat Battle Lagos — Round 2 Finals',
    streamer: '@AfroBeatz',
    city: 'Lagos',
    viewers: 612,
    game: 'Music · Beat Battle',
    category: 'Music',
    tags: ['MUSIC', 'AFROBEATS'],
    isLive: true,
    videoSrc: '/videos/stream-beatbattle.mp4',
    followers: '18.2K',
    bio: 'Afrobeats producer 🎵 | Beat battles every week | Lagos studio sessions live on KultVibe.',
    socials: [
      { platform: 'instagram', handle: 'afrobeatz', url: '#' },
      { platform: 'x',         handle: 'afrobeatz', url: '#' },
      { platform: 'youtube',   handle: 'afrobeatz', url: '#' },
      { platform: 'tiktok',    handle: 'afrobeatz', url: '#' },
    ],
    goal: { label: 'Followers to next milestone', current: 18200, target: 25000 },
  },
  {
    id: 'kelechifc',
    title: 'EA FC Street League — 1v1 Ranked',
    streamer: '@KelechiFC',
    city: 'Port Harcourt',
    viewers: 388,
    game: 'EA FC',
    category: 'Gaming',
    tags: ['FIFA', '1V1'],
    isLive: true,
    videoSrc: '/videos/stream-eafc.mp4',
    followers: '9.4K',
    bio: 'EA FC 1v1 ranked grinder. Port Harcourt. Climbing to Elite division on stream.',
    socials: [
      { platform: 'instagram', handle: 'kelechifc', url: '#' },
      { platform: 'tiktok',    handle: 'kelechifc', url: '#' },
    ],
    goal: { label: 'Followers to next milestone', current: 9400, target: 15000 },
  },

  // --- Offline ---
  {
    id: 'queenplays',
    title: 'Last stream: Valorant Ranked Grind',
    streamer: '@QueenPlays',
    city: 'Lagos',
    viewers: 0,
    game: 'Valorant',
    category: 'Gaming',
    tags: ['RANKED'],
    isLive: false,
    gradientFrom: '#4a044e',
    gradientTo: '#1e1b4b',
    followers: '11.3K',
    bio: 'Valorant Radiant grind. First female Valorant streamer to break top 50 Nigeria.',
    socials: [
      { platform: 'instagram', handle: 'queenplays', url: '#' },
      { platform: 'x',         handle: 'queenplays', url: '#' },
      { platform: 'tiktok',    handle: 'queenplays', url: '#' },
    ],
    goal: { label: 'Followers to Radiant celebration stream', current: 11300, target: 15000 },
  },
  {
    id: 'lagosloot',
    title: 'Last stream: Fortnite Solos — Chapter 6',
    streamer: '@LagosLoot',
    city: 'Lagos',
    viewers: 0,
    game: 'Fortnite',
    category: 'Gaming',
    tags: ['SOLOS'],
    isLive: false,
    gradientFrom: '#164e63',
    gradientTo: '#172554',
    followers: '7.8K',
    bio: 'Fortnite Chapter 6 solos grinder from Lagos. Building to Victory Royale every stream.',
    socials: [
      { platform: 'instagram', handle: 'lagosloot', url: '#' },
      { platform: 'tiktok',    handle: 'lagosloot', url: '#' },
    ],
    goal: { label: 'Subscribers milestone', current: 78, target: 200 },
  },
  {
    id: 'procoderlagos',
    title: 'Last stream: Building a Trading Bot Live',
    streamer: '@ProCoderLagos',
    city: 'Lagos',
    viewers: 0,
    game: 'Tech & Dev',
    category: 'Tech & Dev',
    tags: ['CODING', 'LIVE'],
    isLive: false,
    gradientFrom: '#1e293b',
    gradientTo: '#020617',
    followers: '5.1K',
    bio: 'Building in public. Trading bots, fintech apps, and live coding sessions from Lagos.',
    socials: [
      { platform: 'x',       handle: 'procoderlagos', url: '#' },
      { platform: 'discord', handle: 'procoderlagos', url: '#' },
      { platform: 'youtube', handle: 'procoderlagos', url: '#' },
    ],
    goal: { label: 'GitHub stars on trading bot repo', current: 341, target: 500 },
  },
  {
    id: 'drumkingkano',
    title: 'Last stream: Afrobeats Production Session',
    streamer: '@DrumKingKano',
    city: 'Kano',
    viewers: 0,
    game: 'Music Production',
    category: 'Music',
    tags: ['AFROBEATS'],
    isLive: false,
    gradientFrom: '#78350f',
    gradientTo: '#431407',
    followers: '12.7K',
    bio: 'Afrobeats producer from Kano. Beat battles and studio sessions live every week.',
    socials: [
      { platform: 'instagram', handle: 'drumkingkano', url: '#' },
      { platform: 'x',         handle: 'drumkingkano', url: '#' },
      { platform: 'tiktok',    handle: 'drumkingkano', url: '#' },
      { platform: 'youtube',   handle: 'drumkingkano', url: '#' },
    ],
    goal: { label: 'Streams to beat battle finale', current: 8, target: 12 },
  },
  {
    id: 'naijaninja',
    title: 'Last stream: MK1 Ranked Grind',
    streamer: '@NaijaNinja',
    city: 'Lagos',
    viewers: 0,
    game: 'Mortal Kombat',
    category: 'Gaming',
    tags: ['FIGHTING', '1V1'],
    isLive: false,
    gradientFrom: '#7f1d1d',
    gradientTo: '#4c0519',
    followers: '8.2K',
    bio: 'MK1 Lagos champion. Fighting game specialist. Daily ranked streams.',
    socials: [
      { platform: 'instagram', handle: 'naijaninja', url: '#' },
      { platform: 'tiktok',    handle: 'naijaninja', url: '#' },
    ],
    goal: { label: 'Followers to next milestone', current: 8200, target: 10000 },
  },
  {
    id: 'lenslagos',
    title: 'Last stream: Lagos Street Photography Walk',
    streamer: '@LensLagos',
    city: 'Lagos',
    viewers: 0,
    game: 'Lifestyle',
    category: 'Lifestyle',
    tags: ['VLOG'],
    isLive: false,
    gradientFrom: '#064e3b',
    gradientTo: '#042f2e',
    followers: '8.3K',
    bio: 'Street photographer and creative from Lagos. Live walks through the city every week.',
    socials: [
      { platform: 'instagram', handle: 'lenslagos', url: '#' },
      { platform: 'tiktok',    handle: 'lenslagos', url: '#' },
      { platform: 'x',         handle: 'lenslagos', url: '#' },
    ],
    goal: { label: 'Followers to gallery show', current: 8300, target: 10000 },
  },
  {
    id: 'vibeswithchi',
    title: 'Last stream: Just Chatting with the Squad',
    streamer: '@VibesWithChi',
    city: 'Abuja',
    viewers: 0,
    game: 'Just Chatting',
    category: 'Streaming',
    tags: ['CHAT'],
    isLive: false,
    gradientFrom: '#831843',
    gradientTo: '#4a044e',
    followers: '15.2K',
    bio: 'Just chatting, community building, and good vibes from Abuja. Pull up.',
    socials: [
      { platform: 'instagram', handle: 'vibeswithchi', url: '#' },
      { platform: 'tiktok',    handle: 'vibeswithchi', url: '#' },
      { platform: 'discord',   handle: 'vibeswithchi', url: '#' },
    ],
    goal: { label: 'Community members goal', current: 2150, target: 5000 },
  },
  {
    id: 'aceshooterph',
    title: 'Last stream: Free Fire Diamond Push',
    streamer: '@AceShooterPH',
    city: 'Port Harcourt',
    viewers: 0,
    game: 'Free Fire',
    category: 'Gaming',
    tags: ['RANKED'],
    isLive: false,
    gradientFrom: '#7c2d12',
    gradientTo: '#450a0a',
    followers: '5.9K',
    bio: 'Free Fire solo grinder. Port Harcourt represent. Diamond push daily.',
    socials: [
      { platform: 'instagram', handle: 'aceshooterph', url: '#' },
      { platform: 'tiktok',    handle: 'aceshooterph', url: '#' },
    ],
    goal: { label: 'Followers to next milestone', current: 5900, target: 10000 },
  },
  {
    id: 'queensplays',
    title: 'Last stream: Valorant Agent Grind',
    streamer: '@QueenPlays',
    city: 'Lagos',
    viewers: 0,
    game: 'Valorant',
    category: 'Gaming',
    tags: ['RANKED', 'FEMALE'],
    isLive: false,
    gradientFrom: '#2e1065',
    gradientTo: '#4c1d95',
    followers: '7.1K',
    bio: 'Valorant agent specialist. Lagos female gamer. Breaking barriers daily.',
    socials: [
      { platform: 'instagram', handle: 'queensplays', url: '#' },
      { platform: 'tiktok',    handle: 'queensplays', url: '#' },
    ],
    goal: { label: 'Followers to next milestone', current: 7100, target: 10000 },
  },
  {
    id: 'vibeslenslags',
    title: 'Last stream: Lagos Street Walk',
    streamer: '@VibeLensLagos',
    city: 'Lagos',
    viewers: 0,
    game: 'Lifestyle',
    category: 'Lifestyle',
    tags: ['VLOG', 'PHOTOGRAPHY'],
    isLive: false,
    gradientFrom: '#064e3b',
    gradientTo: '#065f46',
    followers: '6.5K',
    bio: 'Lagos street photographer. Culture documentarian. Visual storyteller.',
    socials: [
      { platform: 'instagram', handle: 'vibeslenslags', url: '#' },
      { platform: 'tiktok',    handle: 'vibeslenslags', url: '#' },
    ],
    goal: { label: 'Followers to gallery show', current: 6500, target: 10000 },
  },
  {
    id: 'abujacoder',
    title: 'Last stream: AI Hackathon Build',
    streamer: '@AbujaCoder',
    city: 'Abuja',
    viewers: 0,
    game: 'Tech & Dev',
    category: 'Tech & Dev',
    tags: ['CODING', 'AI'],
    isLive: false,
    gradientFrom: '#0c4a6e',
    gradientTo: '#075985',
    followers: '4.8K',
    bio: 'AI/ML developer. Hackathon competitor. Building the future from Abuja.',
    socials: [
      { platform: 'x',       handle: 'abujacoder', url: '#' },
      { platform: 'discord', handle: 'abujacoder', url: '#' },
    ],
    goal: { label: 'Followers to next milestone', current: 4800, target: 10000 },
  },
  {
    id: 'kanoking',
    title: 'Last stream: COD Mobile Ranked Grind',
    streamer: '@KanoKing',
    city: 'Kano',
    viewers: 0,
    game: 'COD Mobile',
    category: 'Gaming',
    tags: ['RANKED', 'COD'],
    isLive: false,
    gradientFrom: '#1a2e05',
    gradientTo: '#14532d',
    followers: '3.9K',
    bio: 'COD Mobile grinder from Kano. Northern Nigeria gaming scene represent.',
    socials: [
      { platform: 'instagram', handle: 'kanoking', url: '#' },
      { platform: 'tiktok',    handle: 'kanoking', url: '#' },
    ],
    goal: { label: 'Followers to next milestone', current: 3900, target: 5000 },
  },
  {
    id: 'lagosvibez',
    title: 'Last stream: Just Chatting Session',
    streamer: '@LagosVibes',
    city: 'Lagos',
    viewers: 0,
    game: 'Just Chatting',
    category: 'Streaming',
    tags: ['CHAT', 'VIBES'],
    isLive: false,
    gradientFrom: '#4a044e',
    gradientTo: '#701a75',
    followers: '3.2K',
    bio: 'Just chatting, vibing, entertaining. Lagos energy every stream.',
    socials: [
      { platform: 'instagram', handle: 'lagosvibez', url: '#' },
      { platform: 'tiktok',    handle: 'lagosvibez', url: '#' },
      { platform: 'discord',   handle: 'lagosvibez', url: '#' },
    ],
    goal: { label: 'Community members goal', current: 3200, target: 10000 },
  },
]

export function getStreamById(id: string) {
  return streamsData.find(s => s.id === id)
}
