export interface TournamentData {
  id: string
  name: string
  game: string
  vertical: string
  prize: string
  spotsLeft: number
  totalSpots: number
  imageSrc: string
  entryFee: string
  format: string
  platform: string
  startDate: string
  description: string
  rules: string[]
  prizeBreakdown: { place: string; amount: string }[]
}

export const tournamentsData: TournamentData[] = [
  {
    id: 'codm-cup',
    name: 'Lagos Arena CODM Cup',
    game: 'COD Mobile',
    vertical: 'gaming',
    prize: '₦100,000',
    spotsLeft: 26,
    totalSpots: 128,
    imageSrc: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: 'Squad (4)',
    platform: 'Mobile',
    startDate: 'Jul 5, 2026',
    description: 'The biggest CODM squad showdown in Lagos. Four-man teams battle across Hardpoint, Search & Destroy, and Control to claim the Lagos Arena title.',
    rules: [
      'All participants must have an active KultVibe account before registering.',
      'Teams must use the same in-game squad for all matches — no roster swaps after check-in.',
      'No hacks, mods, or third-party input tools. Violations result in immediate disqualification.',
      'Disconnected players have 3 minutes to rejoin; matches do not pause after that window.',
      'All match results must be screenshotted and submitted within 5 minutes of completion.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦60,000' },
      { place: '2nd', amount: '₦25,000' },
      { place: '3rd', amount: '₦15,000' },
    ],
  },
  {
    id: 'eafc-league',
    name: 'EA FC Street League',
    game: 'EA FC 25',
    vertical: 'gaming',
    prize: '₦50,000',
    spotsLeft: 13,
    totalSpots: 64,
    imageSrc: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=400&fit=crop',
    entryFee: '₦500',
    format: '1v1',
    platform: 'Console / PC',
    startDate: 'Jun 28, 2026',
    description: 'Naija vs the world on the virtual pitch. 1v1 knockout bracket — prove your build is untouchable from group stage to the grand final.',
    rules: [
      'All players must be on EA FC 25 latest patch. No legacy editions.',
      'Matches are played on the platform the player registered with — no switching mid-bracket.',
      'Custom tactics must be set before kick-off; no changes at half-time.',
      'Rage-quitting before 80th minute is recorded as a forfeit.',
      'Disputes are settled by the match replay submitted within 10 minutes of the final whistle.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦30,000' },
      { place: '2nd', amount: '₦13,000' },
      { place: '3rd', amount: '₦7,000' },
    ],
  },
  {
    id: 'mortal-kombat',
    name: 'Mortal Kombat Naija Invitational',
    game: 'Mortal Kombat 1',
    vertical: 'gaming',
    prize: '₦70,000',
    spotsLeft: 8,
    totalSpots: 32,
    imageSrc: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&h=400&fit=crop',
    entryFee: '₦1,000',
    format: '1v1',
    platform: 'Console / PC',
    startDate: 'Jul 12, 2026',
    description: 'Nigeria\'s most brutal 1v1 invitational returns. Best of 3 sets, double-elimination bracket — only one fighter walks out crowned.',
    rules: [
      'Character selection is locked in before each set — no changing after the timer expires.',
      'Kameos must be declared at registration and cannot change during a set.',
      'Standard competitive stage list applies (no stage fatalities in bracket play).',
      'Any use of input macros or turbo controllers results in immediate disqualification.',
      'Grand Final is best of 5 sets with a one-match bracket reset advantage for the winner\'s side.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦42,000' },
      { place: '2nd', amount: '₦18,000' },
      { place: '3rd', amount: '₦10,000' },
    ],
  },
  {
    id: 'pes-classic',
    name: 'PES Classic Revival Cup',
    game: 'eFootball',
    vertical: 'gaming',
    prize: '₦35,000',
    spotsLeft: 22,
    totalSpots: 64,
    imageSrc: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: '1v1',
    platform: 'Mobile / Console',
    startDate: 'Jul 19, 2026',
    description: 'Celebrating the roots of football gaming. Open to all skill levels — if you know your angles and your through-balls, this cup is yours to take.',
    rules: [
      'Default kits and licensed team names must be used — no custom kits in bracket play.',
      'Online matches are played on the player\'s registered platform; PC vs console matchups use a coin-flip for who hosts.',
      'Game speed is set to -1 (one step below default) for all bracket matches.',
      'Connection drops: if a disconnect happens before the 30th minute, the match restarts from 0-0.',
      'Score screenshots are required at full time.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦21,000' },
      { place: '2nd', amount: '₦9,000' },
      { place: '3rd', amount: '₦5,000' },
    ],
  },
  {
    id: 'rocket-league-wa',
    name: 'Rocket League West Africa Open',
    game: 'Rocket League',
    vertical: 'gaming',
    prize: '₦85,000',
    spotsLeft: 16,
    totalSpots: 32,
    imageSrc: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=400&fit=crop',
    entryFee: '₦1,000',
    format: '3v3',
    platform: 'PC / Console',
    startDate: 'Jul 26, 2026',
    description: 'The first official West Africa Rocket League Open. Three-man teams compete through a Swiss round system into a top-8 playoff bracket.',
    rules: [
      'Teams must register as a complete 3-man roster before the deadline.',
      'Substitute players are not permitted once the bracket is seeded.',
      'Matches are played on the Psyonix-certified competitive maps only.',
      'Aerial hacks, speed hacks, or hitbox exploits result in a forfeit of the match.',
      'All matches must be completed within the 30-minute scheduling window or the higher-seeded team advances.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦51,000' },
      { place: '2nd', amount: '₦21,000' },
      { place: '3rd', amount: '₦13,000' },
    ],
  },
  {
    id: 'gta-races',
    name: 'GTA Online Race Circuits Nigeria',
    game: 'GTA Online',
    vertical: 'gaming',
    prize: '₦40,000',
    spotsLeft: 30,
    totalSpots: 64,
    imageSrc: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'Console / PC',
    startDate: 'Aug 2, 2026',
    description: 'Pure stock-vehicle circuit racing in Los Santos — no weaponized vehicles, no power-ups. Just lines, braking points, and raw car control.',
    rules: [
      'All races use stock (non-upgraded) vehicles as specified by the host lobby.',
      'Weaponized, armoured, or flying vehicles are banned from all race sessions.',
      'Deliberate ramming to gain position is penalised with a 5-second time addition per incident.',
      'Race results are final once confirmed in-lobby; no reversals for client-side lag.',
      'Players must join the correct lobby password shared 10 minutes before race start time.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦24,000' },
      { place: '2nd', amount: '₦10,000' },
      { place: '3rd', amount: '₦6,000' },
    ],
  },
  {
    id: 'minecraft-build',
    name: 'Minecraft Build Battle Africa',
    game: 'Minecraft',
    vertical: 'gaming',
    prize: '₦55,000',
    spotsLeft: 45,
    totalSpots: 100,
    imageSrc: 'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'PC / Console / Mobile',
    startDate: 'Aug 9, 2026',
    description: 'Africa\'s first large-scale Minecraft Build Battle. A new theme is revealed at round start — you get 15 minutes to build the most creative interpretation.',
    rules: [
      'All builds must be constructed within the allocated 60x60 plot assigned at game start.',
      'Command blocks, mods, or external auto-builders are strictly prohibited.',
      'Builds must match the announced theme; off-theme entries score 0 for creativity.',
      'Voting is community-based using the in-game voting system; accounts created in the last 7 days cannot vote.',
      'Top 5 builds are reviewed by the judging panel for final placement.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦33,000' },
      { place: '2nd', amount: '₦14,000' },
      { place: '3rd', amount: '₦8,000' },
    ],
  },
  {
    id: 'fortnite-solos',
    name: 'Fortnite Solos Naija Sprint',
    game: 'Fortnite',
    vertical: 'gaming',
    prize: '₦65,000',
    spotsLeft: 60,
    totalSpots: 128,
    imageSrc: 'https://images.unsplash.com/photo-1636622433525-127afcd89f88?w=800&h=400&fit=crop',
    entryFee: '₦500',
    format: 'Solo',
    platform: 'Cross-platform',
    startDate: 'Jul 8, 2026',
    description: 'Sprint through a 3-game points series — placement and eliminations both count. Whoever banks the most points across all three games takes the crown.',
    rules: [
      'Players must link their Epic Games account to KultVibe before the start of Game 1.',
      'All matches are played in the official KultVibe custom lobby code shared at check-in.',
      'Points: Victory Royale = 25 pts; 2nd-5th = 22-18 pts; each elimination = 1 pt.',
      'Third-party scripts, aim-assist exploits, or teaming in solos results in a ban.',
      'Final standings are based on cumulative points across all 3 games.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦39,000' },
      { place: '2nd', amount: '₦16,000' },
      { place: '3rd', amount: '₦10,000' },
    ],
  },
  {
    id: 'valorant-open',
    name: 'Valorant Lagos Open',
    game: 'Valorant',
    vertical: 'fps',
    prize: '₦120,000',
    spotsLeft: 38,
    totalSpots: 64,
    imageSrc: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop',
    entryFee: '₦1,000',
    format: 'Team (5)',
    platform: 'PC',
    startDate: 'Jul 15, 2026',
    description: 'Lagos\'s most competitive Valorant 5v5 open. Double-elimination bracket with standard competitive map pool — every round matters.',
    rules: [
      'Rosters of exactly 5 players plus 1 optional substitute must be declared at registration.',
      'Only the current competitive map pool is used — map veto follows VCT format.',
      'Smurfing (playing on an account below your ranked tier) results in immediate team disqualification.',
      'No communication tools outside of the in-game voice channel are permitted during matches.',
      'Any form of match-fixing will result in a permanent KultVibe ban for all parties involved.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦72,000' },
      { place: '2nd', amount: '₦30,000' },
      { place: '3rd', amount: '₦18,000' },
    ],
  },
  {
    id: 'codm-ranked',
    name: 'COD Mobile Ranked Series S2',
    game: 'COD Mobile',
    vertical: 'fps',
    prize: '₦90,000',
    spotsLeft: 14,
    totalSpots: 64,
    imageSrc: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=400&fit=crop&crop=right',
    entryFee: '₦500',
    format: 'Squad (4)',
    platform: 'Mobile',
    startDate: 'Jun 30, 2026',
    description: 'Season 2 of the CODM Ranked Series — the most consistently competitive mobile FPS bracket in West Africa. Season 1 winner defends the belt.',
    rules: [
      'Minimum in-game rank of Legendary is required to enter — account rank screenshot at registration.',
      'Squads must maintain the same 4-man lineup across all group stage matches.',
      'Mode rotation: Hardpoint (Match 1), Search & Destroy (Match 2), Control (Match 3 if needed).',
      'No emulators — mobile devices only, verified at check-in.',
      'All matches are streamed to KultVibe for broadcast verification.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦54,000' },
      { place: '2nd', amount: '₦23,000' },
      { place: '3rd', amount: '₦13,000' },
    ],
  },
  {
    id: 'cs2-africa',
    name: 'CS2 Africa Qualifiers',
    game: 'CS2',
    vertical: 'fps',
    prize: '₦200,000',
    spotsLeft: 22,
    totalSpots: 32,
    imageSrc: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=800&h=400&fit=crop',
    entryFee: '₦2,000',
    format: 'Team (5)',
    platform: 'PC',
    startDate: 'Aug 16, 2026',
    description: 'The biggest CS2 prize pool on the continent. Top 2 teams earn a spot at the Pan-Africa LAN Finals in Accra — this is your qualifier.',
    rules: [
      'All teams must have a registered Steam account with CS2 Prime status for every player.',
      '128-tick servers are used for all matches; server region is West Africa (Frankfurt fallback if needed).',
      'External voice communication (Discord, etc.) is allowed between maps but not during active rounds.',
      'Pauses are limited to 2 per team per map (30 seconds each) for technical issues only.',
      'Anti-cheat: VAC must be enabled. Any VAC ban in the last 5 years disqualifies the player.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦120,000' },
      { place: '2nd', amount: '₦50,000' },
      { place: '3rd', amount: '₦30,000' },
    ],
  },
  {
    id: 'apex-naija',
    name: 'Apex Legends Naija Cup',
    game: 'Apex Legends',
    vertical: 'fps',
    prize: '₦110,000',
    spotsLeft: 18,
    totalSpots: 60,
    imageSrc: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&h=400&fit=crop&crop=left',
    entryFee: '₦1,000',
    format: 'Trio (3)',
    platform: 'PC / Console',
    startDate: 'Jul 22, 2026',
    description: 'Apex trios compete across 6 games with a points-based ALGS scoring system. Adaptability and zone reads win here more than raw aim.',
    rules: [
      'Trios must register as a complete 3-man team; no fill or substitution after bracket seeding.',
      'Scoring follows ALGS format: placement points + 1 pt per elimination.',
      'Legend selection is open — no restrictions on duplicate legends across teams.',
      'Stream sniping (watching an opponent\'s stream to gain info) results in point deduction per confirmed incident.',
      'Final standings are based on cumulative score across all 6 games.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦66,000' },
      { place: '2nd', amount: '₦28,000' },
      { place: '3rd', amount: '₦16,000' },
    ],
  },
  {
    id: 'overwatch-abuja',
    name: 'Overwatch 2 Abuja Open',
    game: 'Overwatch 2',
    vertical: 'fps',
    prize: '₦75,000',
    spotsLeft: 30,
    totalSpots: 60,
    imageSrc: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: 'Team (5)',
    platform: 'PC / Console',
    startDate: 'Aug 3, 2026',
    description: 'First cross-city OW2 open between Lagos and Abuja teams. Control, Push, and Escort maps are in rotation — versatility across roles is key.',
    rules: [
      'Teams of exactly 5 players with no more than 1 substitute allowed at roster lock.',
      'Competitive mode rules apply: role queue is enforced (1 Tank, 2 DPS, 2 Support).',
      'Map pool is the current OWL season map rotation.',
      'Smurfing is prohibited — accounts must be Diamond 1 or above in the current season.',
      'Substitution requests must be submitted to the TO between maps.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦45,000' },
      { place: '2nd', amount: '₦19,000' },
      { place: '3rd', amount: '₦11,000' },
    ],
  },
  {
    id: 'warzone-ng',
    name: 'Warzone Nigeria Solos',
    game: 'Warzone',
    vertical: 'fps',
    prize: '₦60,000',
    spotsLeft: 55,
    totalSpots: 128,
    imageSrc: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=400&fit=crop&crop=top',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'Cross-platform',
    startDate: 'Jul 1, 2026',
    description: 'Open to all Naija players — 3-game solos series where your lobby placement and kills stack into a leaderboard score. Top gun takes all.',
    rules: [
      'Players must join the private lobby code shared 15 minutes before each match.',
      'Kill-farming (repeatedly eliminating the same player in Gulag) is flagged and penalised.',
      'Loadout drops are enabled; meta loadouts are unrestricted.',
      'Any form of teaming in solos voids your score for that game.',
      'Players are responsible for a stable connection — no results overturned for network issues.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦36,000' },
      { place: '2nd', amount: '₦15,000' },
      { place: '3rd', amount: '₦9,000' },
    ],
  },
  {
    id: 'pubg-royale',
    name: 'PUBG Naija Royale',
    game: 'PUBG Mobile',
    vertical: 'battle-royale',
    prize: '₦250,000',
    spotsLeft: 20,
    totalSpots: 100,
    imageSrc: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=800&h=400&fit=crop',
    entryFee: '₦1,500',
    format: 'Squad (4)',
    platform: 'Mobile',
    startDate: 'Jul 19, 2026',
    description: 'Nigeria\'s highest-prize PUBG Mobile squad tournament. Six matches, PMCO scoring system — the squad with the most consistent placements and kill points wins.',
    rules: [
      'All squad members must link their PUBG Mobile ID to KultVibe before the first match.',
      'Scoring: #1 = 10 pts, #2 = 6 pts, #3-5 = 5 pts, #6-10 = 4 pts; each kill = 1 pt.',
      'Emulators are strictly banned — mobile devices only.',
      'Squads must maintain the same 4 players across all 6 matches; no mid-tournament substitutions.',
      'Teaming with other squads outside of your own is an immediate disqualification.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦150,000' },
      { place: '2nd', amount: '₦63,000' },
      { place: '3rd', amount: '₦37,000' },
    ],
  },
  {
    id: 'freefire-clash',
    name: 'Free Fire Abuja Clash',
    game: 'Free Fire',
    vertical: 'battle-royale',
    prize: '₦60,000',
    spotsLeft: 44,
    totalSpots: 128,
    imageSrc: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=800&h=400&fit=crop&crop=top',
    entryFee: 'Free',
    format: 'Squad (4)',
    platform: 'Mobile',
    startDate: 'Jun 27, 2026',
    description: 'Abuja-region Free Fire squads clash in this open invitation. Low barrier, big energy — even grassroots squads have taken home the cup before.',
    rules: [
      'Squads must have at least 3 registered Abuja-state players (state ID verification at check-in).',
      'No emulators — mobile only. Device checks are done via screen share at lobby creation.',
      'Custom room code and password are shared 20 minutes before each game.',
      'Booyah = 12 pts; placement scale from 10 to 1; each kill = 1 pt.',
      'Final 4 teams from this event qualify for the FF West Africa Regional.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦36,000' },
      { place: '2nd', amount: '₦15,000' },
      { place: '3rd', amount: '₦9,000' },
    ],
  },
  {
    id: 'pubg-squads',
    name: 'PUBG Mobile Squads Port Harcourt',
    game: 'PUBG Mobile',
    vertical: 'battle-royale',
    prize: '₦140,000',
    spotsLeft: 32,
    totalSpots: 80,
    imageSrc: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=800&h=400&fit=crop&crop=top',
    entryFee: '₦1,000',
    format: 'Squad (4)',
    platform: 'Mobile',
    startDate: 'Aug 10, 2026',
    description: 'Port Harcourt\'s signature PUBG Mobile squad event. Five games on Erangel and Miramar with a Grand Final on Sanhok for the top 16 squads.',
    rules: [
      'Team rosters are locked 48 hours before the first match.',
      'Erangel and Miramar maps are used for group stage; Sanhok for the Grand Final.',
      'No vehicle-only camping — teams must engage in combat at least once per zone.',
      'Mobile devices only; emulator detection software is active during all matches.',
      'Prize money is disbursed within 7 working days of the final result confirmation.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦84,000' },
      { place: '2nd', amount: '₦35,000' },
      { place: '3rd', amount: '₦21,000' },
    ],
  },
  {
    id: 'freefire-kano',
    name: 'Free Fire Kano Grand Prix',
    game: 'Free Fire',
    vertical: 'battle-royale',
    prize: '₦50,000',
    spotsLeft: 70,
    totalSpots: 100,
    imageSrc: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=400&fit=crop&crop=bottom',
    entryFee: 'Free',
    format: 'Duo',
    platform: 'Mobile',
    startDate: 'Jul 5, 2026',
    description: 'Duo format Free Fire from Kano — the North\'s biggest mobile gaming event yet. Fast, chaotic, and open to absolutely everyone.',
    rules: [
      'Duos only — solo registration is not accepted.',
      'No emulators. Screen share verification at lobby creation is mandatory.',
      'Custom room: password shared to registered duos 15 minutes before game start.',
      'Points: Booyah = 12, placement scale 10-1, each kill = 1 pt.',
      'If one duo player disconnects, the remaining player may continue solo for that game.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦30,000' },
      { place: '2nd', amount: '₦13,000' },
      { place: '3rd', amount: '₦7,000' },
    ],
  },
  {
    id: 'apex-br-ng',
    name: 'Apex BR Nigeria Championship',
    game: 'Apex Legends',
    vertical: 'battle-royale',
    prize: '₦180,000',
    spotsLeft: 10,
    totalSpots: 60,
    imageSrc: 'https://images.unsplash.com/photo-1636622433525-127afcd89f88?w=800&h=400&fit=crop&crop=top',
    entryFee: '₦1,500',
    format: 'Trio (3)',
    platform: 'PC / Console',
    startDate: 'Aug 23, 2026',
    description: 'The definitive Apex Legends championship in Nigeria. 20 trios, 8 matches, ALGS pro rules. Winners earn automatic consideration for the Africa Invitational.',
    rules: [
      'Teams must be Platinum IV or above in the current ranked season.',
      'Scoring follows the official ALGS circuit rules: match points + kill points per game.',
      'Legend bans: each team submits 1 legend ban per match before lobby creation.',
      'Stream delay of 3 minutes is mandatory for any player broadcasting during the event.',
      'All teams must check in 30 minutes before match start or forfeit their seed.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦108,000' },
      { place: '2nd', amount: '₦45,000' },
      { place: '3rd', amount: '₦27,000' },
    ],
  },
  {
    id: 'nba2k-league',
    name: 'NBA 2K West Africa League',
    game: 'NBA 2K25',
    vertical: 'sports',
    prize: '₦45,000',
    spotsLeft: 6,
    totalSpots: 16,
    imageSrc: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=400&fit=crop',
    entryFee: '₦1,000',
    format: '1v1',
    platform: 'Console / PC',
    startDate: 'Jul 3, 2026',
    description: 'West Africa\'s elite NBA 2K25 players face off in a round-robin league format before a single-elimination playoff. Draft positions are random — team selection is not.',
    rules: [
      'Players must use the 2K25 current season rosters; no custom or classic team edits.',
      'Difficulty is set to Hall of Fame; game speed at default.',
      'Intentionally fouling out your opponent\'s best player repeatedly is flagged as unsportsmanlike.',
      'Lag-related disconnects: if both players agree, the game is restarted from the current score.',
      'Quarter length is 5 minutes for all bracket matches.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦27,000' },
      { place: '2nd', amount: '₦11,000' },
      { place: '3rd', amount: '₦7,000' },
    ],
  },
  {
    id: 'f1-mania',
    name: 'F1 24 West Africa GP',
    game: 'F1 24',
    vertical: 'sports',
    prize: '₦55,000',
    spotsLeft: 18,
    totalSpots: 24,
    imageSrc: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&h=400&fit=crop',
    entryFee: '₦1,000',
    format: 'Solo',
    platform: 'Console / PC',
    startDate: 'Jul 29, 2026',
    description: 'West Africa\'s fastest F1 24 drivers race across 4 iconic circuits — Monaco, Monza, Suzuka, and Spa. A different qualifying style per round keeps it unpredictable.',
    rules: [
      'All assists are set to off (no ABS, no traction control, no racing line).',
      'Cars are spec-locked to the same team per round — announced 24 hours before each race.',
      'Lap 1 collisions: intentional contact at T1 results in a drive-through penalty.',
      'Weather is set to dynamic; players cannot override conditions during the race.',
      'Disconnects within the first 3 laps allow a restart; beyond lap 3 the result stands.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦33,000' },
      { place: '2nd', amount: '₦14,000' },
      { place: '3rd', amount: '₦8,000' },
    ],
  },
  {
    id: 'wwe2k-naija',
    name: 'WWE 2K Nigeria Championship',
    game: 'WWE 2K24',
    vertical: 'sports',
    prize: '₦40,000',
    spotsLeft: 9,
    totalSpots: 32,
    imageSrc: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=400&fit=crop',
    entryFee: '₦500',
    format: '1v1',
    platform: 'Console',
    startDate: 'Aug 6, 2026',
    description: 'Single-elimination on console — your superstar, your moveset, your finish line. The mat doesn\'t care who your favourite is, only who pins first.',
    rules: [
      'Any superstar from the 2K24 base roster can be selected; DLC characters are allowed if both players own them.',
      'Custom superstar creation is not permitted — base and DLC roster only.',
      'Match type: Standard Singles, 3 falls to win.',
      'Exploit glitches (infinite reversal loops, out-of-bounds finishers) invalidate the pinfall.',
      'Grand Final uses a special stipulation match type announced 1 hour before start.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦24,000' },
      { place: '2nd', amount: '₦10,000' },
      { place: '3rd', amount: '₦6,000' },
    ],
  },
  {
    id: 'efootball-league',
    name: 'eFootball Africa League S3',
    game: 'eFootball 24',
    vertical: 'sports',
    prize: '₦30,000',
    spotsLeft: 24,
    totalSpots: 48,
    imageSrc: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=400&fit=crop&crop=top',
    entryFee: 'Free',
    format: '1v1',
    platform: 'Mobile / Console',
    startDate: 'Jul 14, 2026',
    description: 'Season 3 of the Africa eFootball League — the longest-running free-to-enter football sim series on KultVibe. Returning champions face a hungry new bracket.',
    rules: [
      'Teams must be built within the Konami contract cap (no star-stacking loopholes).',
      'Game speed and match length are fixed: normal speed, 10-minute halves.',
      'Cross-platform play is enabled — mobile vs console matches are allowed.',
      'Both players must confirm the result in-app within 15 minutes of the final whistle.',
      'Season 3 carries over the "no same national team twice" rule from Season 2.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦18,000' },
      { place: '2nd', amount: '₦8,000' },
      { place: '3rd', amount: '₦4,000' },
    ],
  },
  {
    id: 'tekken-cup',
    name: 'Tekken 8 West Africa Cup',
    game: 'Tekken 8',
    vertical: 'fighting',
    prize: '₦80,000',
    spotsLeft: 12,
    totalSpots: 32,
    imageSrc: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=400&fit=crop&crop=bottom',
    entryFee: '₦1,000',
    format: '1v1',
    platform: 'Console / PC',
    startDate: 'Jul 26, 2026',
    description: 'West Africa\'s top Tekken players in a double-elimination bracket. If you\'ve been grinding offline locals in Lagos or Accra, this is where you prove it online.',
    rules: [
      'All base roster characters are allowed; DLC characters require both players to confirm ownership.',
      'Heat system is fully enabled; no stage-specific restrictions apply.',
      'Sets are best of 3 in pools, best of 5 from quarter-finals onward.',
      'No pausing mid-round except for genuine technical issues; first pause is a warning, second is a round loss.',
      'Grand Final is run with bracket reset rules (loser\'s side finalist must win two sets).',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦48,000' },
      { place: '2nd', amount: '₦20,000' },
      { place: '3rd', amount: '₦12,000' },
    ],
  },
  {
    id: 'sf6-lagos',
    name: 'Street Fighter 6 Lagos Invitational',
    game: 'SF6',
    vertical: 'fighting',
    prize: '₦95,000',
    spotsLeft: 5,
    totalSpots: 16,
    imageSrc: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&h=400&fit=crop&crop=top',
    entryFee: '₦2,000',
    format: '1v1',
    platform: 'Console / PC',
    startDate: 'Jul 18, 2026',
    description: 'Invitation-only until the last 4 spots open to qualifier submissions. Lagos\'s 12 top-rated SF6 players plus 4 wildcard challengers — 16 entrants, one champion.',
    rules: [
      'Modern controls are prohibited in all invitational sets — classic controls only.',
      'Drive Impact sequences are tracked; excessive looping may be ruled a timeout stall tactic.',
      'Character changes are allowed only between games within a set, not between rounds.',
      'Sets are best of 5 throughout; no exceptions including pools.',
      'Wildcard qualifiers must submit a 5-match video reel for review before their spot is confirmed.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦57,000' },
      { place: '2nd', amount: '₦24,000' },
      { place: '3rd', amount: '₦14,000' },
    ],
  },
  {
    id: 'kof-africa',
    name: 'King of Fighters Africa Open',
    game: 'KOF XV',
    vertical: 'fighting',
    prize: '₦50,000',
    spotsLeft: 10,
    totalSpots: 32,
    imageSrc: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=400&fit=crop&crop=top',
    entryFee: '₦500',
    format: '1v1',
    platform: 'Console / PC',
    startDate: 'Aug 14, 2026',
    description: 'Celebrating the SNK legacy with Africa\'s first dedicated KOF XV open. 3v3 team format — pick your squad wisely because order locks in after registration.',
    rules: [
      'Players pick a team of 3 characters at registration; order cannot be changed once the bracket starts.',
      'DLC characters require both players to own them — if one player doesn\'t, the DLC character is banned for that set.',
      'Sets are best of 3 (each game is 3 rounds to win).',
      'Supers and MAX activations are unrestricted.',
      'Pause abuse (pausing to break opponent\'s momentum) results in an immediate game forfeit.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦30,000' },
      { place: '2nd', amount: '₦13,000' },
      { place: '3rd', amount: '₦7,000' },
    ],
  },
  {
    id: 'beat-battle',
    name: 'Beat Battle Lagos',
    game: 'Music',
    vertical: 'music',
    prize: '₦75,000',
    spotsLeft: 19,
    totalSpots: 64,
    imageSrc: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'Online Submission',
    startDate: 'Jul 11, 2026',
    description: 'Lagos producers submit original beats on a revealed theme — judges rate on originality, arrangement, and feel. The best 8 advance to a live listening party finale.',
    rules: [
      'Beats must be fully original — no uncleared samples. Sample usage must be declared at submission.',
      'Submissions are WAV or FLAC only; minimum 2 minutes, maximum 5 minutes.',
      'The theme is revealed at 9 AM WAT on submission day; you have 6 hours to submit.',
      'Beats previously released publicly (SoundCloud, YouTube, etc.) are ineligible.',
      'Judges score on: Originality (40%), Arrangement (35%), Feel/Vibe (25%).',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦45,000' },
      { place: '2nd', amount: '₦19,000' },
      { place: '3rd', amount: '₦11,000' },
    ],
  },
  {
    id: 'dj-battle-ph',
    name: 'DJ Battle Port Harcourt',
    game: 'DJ Set',
    vertical: 'music',
    prize: '₦60,000',
    spotsLeft: 14,
    totalSpots: 32,
    imageSrc: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=400&fit=crop',
    entryFee: '₦500',
    format: 'Solo',
    platform: 'In-Person',
    startDate: 'Aug 1, 2026',
    description: 'Port Harcourt\'s live DJ battle — 15 minutes on the decks, a mixed crowd judging every mix. Transitions, energy, and reading the room decide who wins.',
    rules: [
      'Each DJ gets exactly 15 minutes; setup time (2 minutes) is separate and not counted.',
      'Live mixing only — pre-recorded sets submitted as your performance result in disqualification.',
      'Contestants must bring their own USB or laptop; the venue provides CDJs and a Pioneer DJM-900.',
      'Genre is open; explicit content must be declared at registration.',
      'Crowd score counts for 30% of the total — judges hold the remaining 70%.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦36,000' },
      { place: '2nd', amount: '₦15,000' },
      { place: '3rd', amount: '₦9,000' },
    ],
  },
  {
    id: 'producer-wars',
    name: 'Producer Wars West Africa',
    game: 'Music Production',
    vertical: 'music',
    prize: '₦110,000',
    spotsLeft: 20,
    totalSpots: 50,
    imageSrc: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&h=400&fit=crop&crop=top',
    entryFee: '₦1,000',
    format: 'Solo',
    platform: 'Online Submission',
    startDate: 'Jul 24, 2026',
    description: 'The West Africa region\'s most respected producer competition. Theme drops at midnight; 12 hours to build, export, and upload. Nothing else matters.',
    rules: [
      'All submissions must be produced entirely within the 12-hour window — session files may be requested for verification.',
      'DAW of choice is unrestricted; hardware synths and VSTs are allowed.',
      'Cleared sample packs are permitted; uncleared samples must be credited and may affect scoring.',
      'Minimum tempo: 70 BPM. No minimum/maximum track length.',
      'Top 10 producers are invited to a live virtual listening session where they discuss their process.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦66,000' },
      { place: '2nd', amount: '₦28,000' },
      { place: '3rd', amount: '₦16,000' },
    ],
  },
  {
    id: 'band-clash',
    name: 'Band Clash Abuja Edition',
    game: 'Live Band',
    vertical: 'music',
    prize: '₦80,000',
    spotsLeft: 8,
    totalSpots: 20,
    imageSrc: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&h=400&fit=crop',
    entryFee: '₦2,000',
    format: 'Band (3-7)',
    platform: 'In-Person',
    startDate: 'Aug 30, 2026',
    description: 'Abuja bands compete in 2 rounds: a cover set and an original. The crowd votes after each round — the highest combined score wins the clash.',
    rules: [
      'Bands must have between 3 and 7 members; backing tracks are not permitted.',
      'Round 1 (cover): any song, performed live, max 6 minutes.',
      'Round 2 (original): an original composition only, max 8 minutes.',
      'Setup and teardown time is 10 minutes each; exceeding this reduces scoring by 5% per minute over.',
      'Explicit language must be declared at registration; discretion is expected given the mixed audience.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦48,000' },
      { place: '2nd', amount: '₦20,000' },
      { place: '3rd', amount: '₦12,000' },
    ],
  },
  {
    id: 'afrobeats-open',
    name: 'Afrobeats Producers Open',
    game: 'Music Production',
    vertical: 'afrobeats',
    prize: '₦90,000',
    spotsLeft: 8,
    totalSpots: 32,
    imageSrc: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'Online Submission',
    startDate: 'Jul 6, 2026',
    description: 'Afrobeats-only producer competition — the sub-genre brief is announced at drop. From Alte to street pop, show what the continent sounds like right now.',
    rules: [
      'All beats must be Afrobeats or an Afrobeats sub-genre — no hip-hop or pop crossovers that stray from the brief.',
      'Submission window is 8 hours from theme drop.',
      'Vocals are allowed but must be original recordings — no recycled vocal chops from known tracks.',
      'WAV or FLAC only, 44.1kHz minimum.',
      'Winners grant KultVibe a non-exclusive right to feature their beat in platform marketing for 3 months.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦54,000' },
      { place: '2nd', amount: '₦23,000' },
      { place: '3rd', amount: '₦13,000' },
    ],
  },
  {
    id: 'naija-vibes',
    name: 'Naija Vibes Beat Competition',
    game: 'Beat Making',
    vertical: 'afrobeats',
    prize: '₦55,000',
    spotsLeft: 22,
    totalSpots: 50,
    imageSrc: 'https://images.unsplash.com/photo-1520869562399-e772f042f422?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'Online Submission',
    startDate: 'Aug 7, 2026',
    description: 'Celebrating the sound of Nigeria. Open to all producers — if your beat makes someone move in Lagos at 2 AM, it belongs here.',
    rules: [
      'Genre must be clearly Afrobeats, Afropop, or Afro-fusion.',
      'No more than 4 bars of any sample that isn\'t original or cleared.',
      'Submissions are judged blind — producer names are not shared with judges until scoring is complete.',
      'Judges score on: Groove (35%), Arrangement (35%), Originality (30%).',
      'Top 5 beats are featured on the KultVibe Afrobeats playlist for 30 days.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦33,000' },
      { place: '2nd', amount: '₦14,000' },
      { place: '3rd', amount: '₦8,000' },
    ],
  },
  {
    id: 'afro-mixtape',
    name: 'Afro Mixtape Challenge Season 2',
    game: 'DJ / Mix',
    vertical: 'afrobeats',
    prize: '₦45,000',
    spotsLeft: 35,
    totalSpots: 60,
    imageSrc: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=800&h=400&fit=crop&crop=top',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'Online Submission',
    startDate: 'Jul 20, 2026',
    description: 'Submit a 30-minute Afrobeats mixtape — all transitions, sequencing, and selection are judged. Season 1 winner is back to defend but the competition has grown.',
    rules: [
      'Mixtape must be between 28 and 32 minutes long.',
      'All tracks must be Afrobeats or Afrobeats-adjacent; maximum 2 non-Afrobeats tracks allowed.',
      'Live mixing only — no DJ software "auto-mix" modes without creative input.',
      'Upload format: MP3 at 320kbps minimum.',
      'Top 5 mixes are broadcast live on KultVibe Streams during the reveal event.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦27,000' },
      { place: '2nd', amount: '₦11,000' },
      { place: '3rd', amount: '₦7,000' },
    ],
  },
  {
    id: 'ctf-challenge',
    name: 'Naija CTF Challenge',
    game: 'Cybersecurity',
    vertical: 'tech',
    prize: '₦150,000',
    spotsLeft: 64,
    totalSpots: 64,
    imageSrc: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'Online',
    startDate: 'Jul 12, 2026',
    description: 'A 24-hour Capture The Flag event across web exploitation, reverse engineering, cryptography, and OSINT categories. Every flag is worth points — speed and breadth win.',
    rules: [
      'Sharing flags, solutions, or hints with other competitors during the event is grounds for disqualification.',
      'All challenges run on isolated KultVibe-hosted infrastructure — only attack designated targets.',
      'Attacking the scoreboard, challenge servers, or other players\' machines is strictly prohibited.',
      'Teams are capped at 1 player for this event (solo only).',
      'Top 3 finishers must complete a 10-minute writeup call with the panel to confirm their own work.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦90,000' },
      { place: '2nd', amount: '₦38,000' },
      { place: '3rd', amount: '₦22,000' },
    ],
  },
  {
    id: 'ai-showdown',
    name: 'AI Model Showdown Lagos',
    game: 'AI / ML',
    vertical: 'tech',
    prize: '₦200,000',
    spotsLeft: 40,
    totalSpots: 50,
    imageSrc: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=400&fit=crop',
    entryFee: '₦2,000',
    format: 'Solo / Team (up to 3)',
    platform: 'Online',
    startDate: 'Aug 22, 2026',
    description: 'Build the best-performing ML model on a revealed dataset. 48 hours, your stack, and one submission. Judges evaluate accuracy, efficiency, and approach clarity.',
    rules: [
      'Dataset is released at the start of the 48-hour window; no prior access is given.',
      'Submissions must include a model file, inference script, and a 1-page methodology note.',
      'Pre-trained foundation models are allowed as a base but must be fine-tuned on the provided dataset.',
      'Evaluation metric is announced with the dataset; optimize only for that metric.',
      'Teams of up to 3 are allowed; solo entries are weighted slightly higher in the originality score.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦120,000' },
      { place: '2nd', amount: '₦50,000' },
      { place: '3rd', amount: '₦30,000' },
    ],
  },
  {
    id: 'open-source-sprint',
    name: 'Open Source Sprint Africa',
    game: 'Open Source',
    vertical: 'tech',
    prize: '₦80,000',
    spotsLeft: 55,
    totalSpots: 80,
    imageSrc: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: 'Solo / Team (up to 2)',
    platform: 'Online',
    startDate: 'Jul 17, 2026',
    description: 'Pick a repo from the curated list of African-built open source projects and ship a meaningful contribution in 72 hours. Pull requests that get merged win points.',
    rules: [
      'Contributions must target projects on the official KultVibe Sprint list — external repos are ineligible.',
      'AI-generated code that isn\'t reviewed and understood by the contributor will be flagged during review.',
      'Each merged PR earns points based on scope: bug fix (5 pts), feature (15 pts), docs (3 pts).',
      'Duplicate PRs addressing the same issue score zero — first merged PR takes the points.',
      'Point disputes are resolved by the project maintainer\'s judgement, which is final.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦48,000' },
      { place: '2nd', amount: '₦20,000' },
      { place: '3rd', amount: '₦12,000' },
    ],
  },
  {
    id: 'devops-cup',
    name: 'DevOps and Cloud Nigeria Cup',
    game: 'Cloud / DevOps',
    vertical: 'tech',
    prize: '₦120,000',
    spotsLeft: 30,
    totalSpots: 40,
    imageSrc: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&h=400&fit=crop',
    entryFee: '₦1,500',
    format: 'Solo / Team (up to 2)',
    platform: 'Online',
    startDate: 'Aug 28, 2026',
    description: 'Design, deploy, and document a cloud-native architecture for a given problem statement. Scored on reliability, cost, and how well it scales. Cloud provider is your choice.',
    rules: [
      'Architecture must be deployable from scratch using only the submitted IaC code.',
      'Any major cloud provider (AWS, GCP, Azure) or African cloud provider is permitted.',
      'Solutions are evaluated in a sandboxed environment — credentials must be temporary and scoped.',
      'Judging criteria: Reliability (30%), Cost efficiency (25%), Scalability (25%), Documentation (20%).',
      'Submissions are accepted only through the KultVibe DevOps Cup portal before the deadline.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦72,000' },
      { place: '2nd', amount: '₦30,000' },
      { place: '3rd', amount: '₦18,000' },
    ],
  },
  {
    id: 'hackathon-lagos',
    name: 'KultVibe Hackathon Lagos',
    game: 'Coding',
    vertical: 'coding',
    prize: '₦300,000',
    spotsLeft: 50,
    totalSpots: 80,
    imageSrc: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: 'Team (2-4)',
    platform: 'In-Person / Online',
    startDate: 'Aug 16, 2026',
    description: 'KultVibe\'s flagship hackathon. 36 hours to build something that solves a real African problem. Judges include founders, VCs, and engineers who have shipped at scale.',
    rules: [
      'Teams of 2-4 people; all members must register individually and link to the team before the deadline.',
      'Projects must be built from scratch during the hackathon — no pre-built repos or recycled projects.',
      'All code must be pushed to the provided GitHub organisation repo before the submission window closes.',
      'Pitches are 3 minutes + 2 minutes Q&A; demos must be live (no pre-recorded videos).',
      'Judging criteria: Impact (30%), Technical execution (30%), Innovation (20%), Presentation (20%).',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦180,000' },
      { place: '2nd', amount: '₦75,000' },
      { place: '3rd', amount: '₦45,000' },
    ],
  },
  {
    id: 'leetcode-battle',
    name: 'LeetCode Battle West Africa',
    game: 'Algorithms',
    vertical: 'coding',
    prize: '₦85,000',
    spotsLeft: 42,
    totalSpots: 64,
    imageSrc: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&h=400&fit=crop',
    entryFee: '₦500',
    format: 'Solo',
    platform: 'Online',
    startDate: 'Jul 25, 2026',
    description: '5 algorithm problems, 90 minutes, any language. Partial credit for passing test cases — brute force gets you something, optimal solutions get you everything.',
    rules: [
      'Problems span Easy (1), Medium (2), and Hard (2) difficulty categories.',
      'Any programming language supported by the LeetCode judge is permitted.',
      'AI code generation tools (Copilot, ChatGPT) are not allowed during the competition window.',
      'Score is based on test cases passed x problem weight; time is a tiebreaker for equal scores.',
      'Plagiarism detection runs post-competition; matched submissions are disqualified retroactively.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦51,000' },
      { place: '2nd', amount: '₦21,000' },
      { place: '3rd', amount: '₦13,000' },
    ],
  },
  {
    id: 'web-dev-wars',
    name: 'Web Dev Wars UI Sprint',
    game: 'Web Dev',
    vertical: 'coding',
    prize: '₦70,000',
    spotsLeft: 28,
    totalSpots: 50,
    imageSrc: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&h=400&fit=crop&crop=top',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'Online',
    startDate: 'Jul 31, 2026',
    description: 'A design brief drops at noon. You have 4 hours to build a pixel-perfect, responsive UI with working interactions. Stack is your choice — output quality is everything.',
    rules: [
      'The design brief (Figma link or spec sheet) is shared at exactly 12:00 WAT.',
      'Any frontend framework or vanilla stack is accepted.',
      'Submissions must include a live URL (Vercel, Netlify, etc.) and a public GitHub repo.',
      'Pixel accuracy, responsiveness, and micro-interactions each carry equal weight in scoring.',
      'AI-generated UI code is allowed but must be significantly modified — copy-paste from v0 or Lovable without customisation scores zero.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦42,000' },
      { place: '2nd', amount: '₦18,000' },
      { place: '3rd', amount: '₦10,000' },
    ],
  },
  {
    id: 'mlbb-ng',
    name: 'Mobile Legends Nigeria Open',
    game: 'Mobile Legends',
    vertical: 'moba',
    prize: '₦130,000',
    spotsLeft: 16,
    totalSpots: 40,
    imageSrc: 'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=800&h=400&fit=crop&crop=top',
    entryFee: '₦1,000',
    format: 'Team (5)',
    platform: 'Mobile',
    startDate: 'Aug 9, 2026',
    description: 'Nigeria\'s largest Mobile Legends 5v5 open. Standard draft pick, competitive rank map pool, and a prize pool that puts offline LAN tournaments to shame.',
    rules: [
      'Teams of exactly 5 players with a declared support player and captain must be registered.',
      'Draft pick format with one ban per side in the first round; two bans per side from quarter-finals onward.',
      'No emulators — all players must be on mobile devices, verified via screen share.',
      'Minimum account rank: Epic. Accounts below this rank are not eligible regardless of skill.',
      'Team substitutions can only happen between matches, not mid-series.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦78,000' },
      { place: '2nd', amount: '₦33,000' },
      { place: '3rd', amount: '₦19,000' },
    ],
  },
  {
    id: 'lol-africa',
    name: 'League of Legends Africa Rift',
    game: 'League of Legends',
    vertical: 'moba',
    prize: '₦180,000',
    spotsLeft: 20,
    totalSpots: 50,
    imageSrc: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=400&fit=crop&crop=bottom',
    entryFee: '₦2,000',
    format: 'Team (5)',
    platform: 'PC',
    startDate: 'Aug 29, 2026',
    description: 'Africa\'s most ambitious LoL 5v5 tournament. All 5 roles must be declared at draft — this is a team game and the meta knows it.',
    rules: [
      'Standard blind tournament draft; all players must be on the EUW or EUNE server for match play.',
      'Smurfing is penalised: any player found on an account below their main rank is banned.',
      'Games are played on 5.0.0 patch or latest stable; no hotfix patches trigger replays.',
      'Remake rules follow Riot\'s competitive remake policy (disconnect within 3 minutes, before first blood).',
      'Top team earns an invitation to the KultVibe Africa All-Stars invitational in Q4 2026.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦108,000' },
      { place: '2nd', amount: '₦45,000' },
      { place: '3rd', amount: '₦27,000' },
    ],
  },
  {
    id: 'chess-ng',
    name: 'Online Chess Blitz Nigeria',
    game: 'Chess',
    vertical: 'lifestyle',
    prize: '₦30,000',
    spotsLeft: 80,
    totalSpots: 200,
    imageSrc: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=400&fit=crop&crop=top',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'Online (Chess.com / Lichess)',
    startDate: 'Jul 5, 2026',
    description: '3+2 blitz Swiss tournament — 7 rounds, one sitting, open to all Nigerian Chess.com or Lichess accounts. No rating floor, just results.',
    rules: [
      'Players must connect their Chess.com or Lichess account to KultVibe before the tournament start.',
      'Time control: 3 minutes + 2 seconds increment per move.',
      'Swiss system: 7 rounds, no re-pairings. Tiebreaker is Buchholz score.',
      'Cheating detection uses both platform engine reports and KultVibe\'s post-game analysis.',
      'Results are final 30 minutes after the last round completes.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦18,000' },
      { place: '2nd', amount: '₦8,000' },
      { place: '3rd', amount: '₦4,000' },
    ],
  },
  {
    id: 'trivia-lagos',
    name: 'Lagos Trivia Night Championship',
    game: 'Trivia',
    vertical: 'lifestyle',
    prize: '₦25,000',
    spotsLeft: 60,
    totalSpots: 100,
    imageSrc: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&h=400&fit=crop&crop=top',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'Online',
    startDate: 'Jun 27, 2026',
    description: '40 questions across pop culture, football, Naija history, science, and gaming. You have 20 seconds per question — fastest correct answer earns bonus points.',
    rules: [
      'All participants must be connected to the KultVibe Trivia room via the event link.',
      'No search engines or external help — this is a memory-and-speed competition.',
      'Speed bonus: questions answered within 5 seconds earn 1.5x the base points.',
      'Disconnections during a question result in 0 points for that question, no exceptions.',
      'Final standings are based on cumulative score; speed is only a tiebreaker for equal scores.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦15,000' },
      { place: '2nd', amount: '₦6,000' },
      { place: '3rd', amount: '₦4,000' },
    ],
  },
  {
    id: 'stream-wars',
    name: 'KultVibe Stream Wars',
    game: 'Live Streaming',
    vertical: 'streaming',
    prize: '₦100,000',
    spotsLeft: 48,
    totalSpots: 60,
    imageSrc: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=400&fit=crop&crop=top',
    entryFee: '₦500',
    format: 'Solo',
    platform: 'KultVibe Streams',
    startDate: 'Aug 1, 2026',
    description: '7-day streaming competition on KultVibe. Accumulate peak concurrent viewers, gifted subs, and stream hours. The creator who moves the numbers most wins.',
    rules: [
      'All streams must be broadcast exclusively on KultVibe Streams for the 7-day competition window.',
      'Metric weights: Peak concurrent viewers (40%), Gifted subs received (35%), Total stream hours (25%).',
      'Purchased or bot-inflated viewership is grounds for permanent ban and prize forfeiture.',
      'Minimum 3 streaming sessions of at least 2 hours each are required to qualify for final ranking.',
      'Explicit content, harassment, or hateful conduct results in immediate disqualification.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦60,000' },
      { place: '2nd', amount: '₦25,000' },
      { place: '3rd', amount: '₦15,000' },
    ],
  },
  {
    id: 'watch-party-cup',
    name: 'Watch Party Engagement Cup',
    game: 'Streaming',
    vertical: 'streaming',
    prize: '₦50,000',
    spotsLeft: 35,
    totalSpots: 50,
    imageSrc: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=800&h=400&fit=crop&crop=top',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'KultVibe Streams',
    startDate: 'Jul 13, 2026',
    description: 'Host the most engaging watch party on KultVibe — chat activity, watch time, and raid count determine your score. The host who brings the room to life, wins.',
    rules: [
      'Watch party must be hosted on KultVibe Streams using an officially registered Watch Party event.',
      'Scoring: Average concurrent viewers (30%), Chat messages per minute (35%), Raids received (20%), Watch time per viewer (15%).',
      'You may not pay viewers to stay — organic engagement only.',
      'Watch parties must be at least 90 minutes long to count for scoring.',
      'Participants are ranked by total score at the end of the 7-day competition window.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦30,000' },
      { place: '2nd', amount: '₦13,000' },
      { place: '3rd', amount: '₦7,000' },
    ],
  },
  {
    id: 'creator-cup',
    name: 'KultVibe Creator Cup',
    game: 'Content Creation',
    vertical: 'creator',
    prize: '₦200,000',
    spotsLeft: 100,
    totalSpots: 100,
    imageSrc: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=400&fit=crop',
    entryFee: 'Free',
    format: 'Solo',
    platform: 'KultVibe',
    startDate: 'Sep 1, 2026',
    description: 'KultVibe\'s flagship creator competition. Post original content on the platform across a 30-day window — the most engaging creator walks away with ₦200,000 and a brand deal.',
    rules: [
      'Content must be original and posted directly on KultVibe during the 30-day window.',
      'Engagement score: likes (20%), comments (25%), shares (25%), saves (30%).',
      'Reposts of content from other platforms without original value added score 0.',
      'A minimum of 12 posts during the 30 days is required to qualify for final ranking.',
      'Judges review the top 10 by score and make final adjustments for content quality.',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦120,000' },
      { place: '2nd', amount: '₦50,000' },
      { place: '3rd', amount: '₦30,000' },
    ],
  },
  {
    id: 'short-film-ng',
    name: 'Short Film Creator Sprint',
    game: 'Video Production',
    vertical: 'creator',
    prize: '₦150,000',
    spotsLeft: 25,
    totalSpots: 40,
    imageSrc: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=400&fit=crop&crop=top',
    entryFee: '₦1,000',
    format: 'Solo / Team (up to 3)',
    platform: 'Online Submission',
    startDate: 'Aug 25, 2026',
    description: 'Submit a short film of 3-10 minutes on a theme revealed at the start of the 72-hour window. Storytelling, cinematography, and editing — all judged equally.',
    rules: [
      'Films must be between 3 and 10 minutes including credits.',
      'The theme is revealed at 12:00 WAT on the start date; filming must begin after the reveal.',
      'Footage shot before the theme reveal is not permitted.',
      'Submission format: MP4 or MOV, minimum 1080p resolution.',
      'Judging criteria: Storytelling (35%), Cinematography (30%), Editing (20%), Theme relevance (15%).',
    ],
    prizeBreakdown: [
      { place: '1st', amount: '₦90,000' },
      { place: '2nd', amount: '₦38,000' },
      { place: '3rd', amount: '₦22,000' },
    ],
  },
]

export function getTournamentById(id: string) {
  return tournamentsData.find(t => t.id === id)
}
